const LandingPadsActionTypes = {
    FETCH_LANDINGPADS_START: 'FETCH_LANDINGPADS_START',
    FETCH_LANDINGPADS_SUCCESS: 'FETCH_LANDINGPADS_SUCCESS',
    FETCH_LANDINGPADS_FAILURE: 'FETCH_LANDINGPADS_FAILURE'
}

export default LandingPadsActionTypes;