const CapsulesActionTypes = {
    FETCH_CAPSULES_START: 'FETCH_CAPSULES_START',
    FETCH_CAPSULES_SUCCESS: 'FETCH_CAPSULES_SUCCESS',
    FETCH_CAPSULES_FAILURE: 'FETCH_CAPSULES_FAILURE',
}

export default CapsulesActionTypes;